@startuml classes diagram

class KBD_LED
{
    +execute()
}

'----- COLORS -----
class COLORS
{
    -colors : string = "white"
}

enum Color
{
    WHITE
    RED
    GREEN
    BLUE
}

COLORS [colors] --> "1..*" Color

'----- TIMES -----
class TIMES
{
    -times : string
    +times[] : int
}

note top of TIMES
    {0<times[i]<100}
    {time[0]=0}
    {last time[i]=100}
end note

'----- ANIMATION -----
class ANIMATION
{
    -type : string = "steady"
    -speed : string = "slow"
}

enum AnimationType
{
    OFF
    STEADY
    BREATH
}

ANIMATION [type] --> "1" AnimationType

enum AnimationSpeed
{
    SLOW
    MEDIUM
    FAST
}

ANIMATION [speed] --> "1" AnimationSpeed

'----- KEYFRAME -----
class KEYFRAME
{
    +time : int
}

note left :{time 0 to 100}

note as N1
    {time ordered}
    {first kf=0}
    {last kf=100}
    {first color=last color}
end note

KEYFRAME [color] --> "1" Color

KBD_LED .. N1
N1 .. KEYFRAME

KBD_LED "1" *--> "1" COLORS
KBD_LED "1" *--> "1" ANIMATION
KBD_LED "1" *--> "2..10\n{ordered}" KEYFRAME
KBD_LED "1" *--> "1" TIMES

@enduml