@startuml classes
    class KBD_LED
    {
        +execute()
    }

    enum Color
    {
        WHITE
        RED
        GREEN
        BLUE
    }

'----- COLORS -----
    class COLORS
    {
        -colors[] : string = "white"
    }

    COLORS [colors] --> "1..*" Color

'----- ANIMATIONS -----
    class ANIMATIONS
    {
        -animation : string = "steady"
    }

        enum Animation
    {
        OFF
        STEADY
        BREATH
    }

    ANIMATIONS [animation] --> "1" Animation

'----- SPEED -----
    enum Speed
    {
        SLOW
        MEDIUM
        FAST
    }

    class ANIM_SPEED
    {
        -speed : string = "slow"
    }

    ANIM_SPEED [speed] --> "1" Speed

'----- KEYFRAME -----
    class KEYFRAME
    {
        -time : string
        -color : string = "white"
    }

    note left :{0<time<100}
    note as N1
        {time ordered}
        {first kf=0}
        {last kf=100}
        {first color=last color}
    end note

    KEYFRAME [color] --> "1" Color

    KBD_LED .. N1
    N1 .. KEYFRAME

    KBD_LED "1" *--> "1" COLORS
    KBD_LED "1" *--> "1" ANIMATIONS
    KBD_LED "1" *--> "1" ANIM_SPEED
    KBD_LED "1" *--> "0..10" KEYFRAME

@enduml